/**
 * `prd refine` command — reads an existing PRD and outputs
 * a refined version with gap analysis and inline suggestions.
 */

import { Command } from 'commander';
import ora from 'ora';

import { generate, resolveModel } from '../lib/claude.js';
import { REFINE_SYSTEM_PROMPT, buildRefinePrompt } from '../lib/prompts.js';
import { readPrd, savePrd } from '../lib/file.js';
import {
  brand,
  printBanner,
  printHeader,
  printSuccess,
  printInfo,
  printError,
  printFilePath,
  printStats,
  printFooter,
} from '../lib/format.js';

interface RefineOptions {
  model?: string;
  output?: string;
}

export function registerRefineCommand(program: Command): void {
  program
    .command('refine <file>')
    .description('Refine an existing PRD — identify gaps, strengthen assumptions')
    .option(
      '-m, --model <model>',
      'Claude model: sonnet (default), opus, haiku'
    )
    .option(
      '-o, --output <dir>',
      'Output directory',
      'prd-output'
    )
    .action(async (file: string, opts: RefineOptions) => {
      printBanner();
      printHeader('PRD Refinement');

      // Read existing PRD
      let existingContent: string;
      try {
        existingContent = readPrd(file);
        printSuccess(`Loaded: ${file}`);
        printInfo(`${existingContent.split('\n').length} lines, ${existingContent.split(/\s+/).length} words`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        printError(message);
        process.exit(1);
      }

      const model = resolveModel(opts.model);
      printInfo(`Model: ${model}`);

      const spinner = ora({
        text: brand.dimGold('Analyzing and refining your PRD...'),
        spinner: 'dots12',
        color: 'yellow',
      }).start();

      const startTime = Date.now();

      try {
        const userPrompt = buildRefinePrompt(existingContent);

        let refined = await generate({
          systemPrompt: REFINE_SYSTEM_PROMPT,
          userPrompt,
          model,
          maxTokens: 8192,
        });

        const duration = Date.now() - startTime;
        spinner.stop();

        // Add a header indicating this is a refined version
        if (!refined.startsWith('# ')) {
          refined = `# Refined PRD\n\n> This is a reviewed and refined version generated by prd-cli.\n> Look for **[PRD REVIEW]** tags for inline suggestions.\n\n${refined}`;
        }

        // Save refined version
        const savedPath = savePrd(refined, opts.output);

        console.log('');
        printSuccess('PRD refined successfully!');
        printFilePath('Original', file);
        printFilePath('Refined', savedPath);
        printStats(refined, duration);
        printFooter();
      } catch (error) {
        spinner.stop();
        const message = error instanceof Error ? error.message : String(error);

        if (message.includes('API key') || message.includes('ANTHROPIC_API_KEY')) {
          printError('Missing API key.');
          printInfo('Set your Anthropic API key:');
          console.log(brand.gold('  export ANTHROPIC_API_KEY="sk-ant-..."'));
        } else {
          printError(`Refinement failed: ${message}`);
        }
        process.exit(1);
      }
    });
}
